version: '2'
services:
  node:
    image: node:8-alpine
    user: node
    working_dir: /home/node/app
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: npm run docker-watch
    depends_on:
      - mongodb
  #    - postgres
  mongodb:
    image: mongo:latest # mongo-alpine doesn't work correctly
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # quiet
  # postgres:
  #   build:
  #     context: ./docker/images/postgres
  #   volumes:
  #     - willcoin_postgres:/var/lib/postgresql/data
  #   env_file:
  #     - docker/env/postgres.dev.env
  #   ports:
  #     - 5432:5432
  geth:
    image: ethereum/client-go:alpine
    command: "--fast --rpc --rpcaddr '0.0.0.0' --testnet"
    labels:
      - com.storm.type=eth
    environment:
      - affinity:com.storm.type!=eth
    environment:
      SERVICE_NAME: eth
      SERVICE_TAGS: testnet
    volumes:
      - ethereum_volume:/root
    ports:
      - 8545:8545
      - 30303:30303
volumes:
  willcoin_postgres:
  ethereum_volume:
